### ISSUE TITLE
Provide a setter for public property "localfile"

### ISSUE THREAD

**Issue by sweiguny** [GaretJax/phpbrowscap#76]
I am using symfony and phpbrowscap as service defined in `services.yml`.

currently, my definition in `services.yml` look like this:
```
browscap:
        class: phpbrowscap\Browscap
        arguments:
            - %browscap_cache_dir%
```

I'd like to set the property "localfile" initially, but thats not possible in `services.yml`, because it only allows to inject variables in the constructor and/or additionally calling a certain setter.

having this setter would help here.
i personally don't see a reason for not having a setter.
